import type { ScenarioInput } from "./types";

export const FIXED_NPS = 42;

export type DefaultLocationRecord = {
  name: string;
  input: ScenarioInput;
};

// Default/fallback portfolio used when no spreadsheet has been imported on this device.
// Source: "pf uploadnj 815.xlsx" — sheet "ERS Test Inputs" (17 locations).
export const DEFAULT_LOCATION_DATASET: readonly DefaultLocationRecord[] = [
  {
    name: "Brick 55",
    input: {
      totalMonitoredAssets: 166,
      workOrdersStarted: 17,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 26.9,
      completedEquipmentWorkOrders: 29,
      totalOpenEquipmentWorkOrders: 6,
      olderThan15Days: 3,
      olderThan30Days: 2,
      olderThan45Days: 1,
      assetsWith3PlusRepairs: 1,
    },
  },
  {
    name: "Brick 58",
    input: {
      totalMonitoredAssets: 177,
      workOrdersStarted: 38,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 11.43,
      completedEquipmentWorkOrders: 47,
      totalOpenEquipmentWorkOrders: 2,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 1,
    },
  },
  {
    name: "Barnegot",
    input: {
      totalMonitoredAssets: 210,
      workOrdersStarted: 46,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 6.44,
      completedEquipmentWorkOrders: 52,
      totalOpenEquipmentWorkOrders: 0,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 2,
    },
  },
  {
    name: "Bayonne",
    input: {
      totalMonitoredAssets: 144,
      workOrdersStarted: 17,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 14.79,
      completedEquipmentWorkOrders: 32,
      totalOpenEquipmentWorkOrders: 0,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 1,
    },
  },
  {
    name: "Edison",
    input: {
      totalMonitoredAssets: 141,
      workOrdersStarted: 6,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 12.29,
      completedEquipmentWorkOrders: 21,
      totalOpenEquipmentWorkOrders: 1,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 0,
    },
  },
  {
    name: "Freehold",
    input: {
      totalMonitoredAssets: 166,
      workOrdersStarted: 46,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 7.66,
      completedEquipmentWorkOrders: 50,
      totalOpenEquipmentWorkOrders: 1,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 1,
    },
  },
  {
    name: "Ocean",
    input: {
      totalMonitoredAssets: 221,
      workOrdersStarted: 33,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 12.45,
      completedEquipmentWorkOrders: 51,
      totalOpenEquipmentWorkOrders: 2,
      olderThan15Days: 1,
      olderThan30Days: 1,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 1,
    },
  },
  {
    name: "Shrewsbury",
    input: {
      totalMonitoredAssets: 158,
      workOrdersStarted: 8,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 18.65,
      completedEquipmentWorkOrders: 23,
      totalOpenEquipmentWorkOrders: 0,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 0,
    },
  },
  {
    name: "Toms River 37",
    input: {
      totalMonitoredAssets: 168,
      workOrdersStarted: 35,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 5.29,
      completedEquipmentWorkOrders: 49,
      totalOpenEquipmentWorkOrders: 0,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 0,
    },
  },
  {
    name: "Toms River",
    input: {
      totalMonitoredAssets: 146,
      workOrdersStarted: 17,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 12.14,
      completedEquipmentWorkOrders: 22,
      totalOpenEquipmentWorkOrders: 1,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 0,
    },
  },
  {
    name: "Wall",
    input: {
      totalMonitoredAssets: 128,
      workOrdersStarted: 21,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 21.11,
      completedEquipmentWorkOrders: 18,
      totalOpenEquipmentWorkOrders: 4,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 0,
    },
  },
  {
    name: "Hoboken",
    input: {
      totalMonitoredAssets: 111,
      workOrdersStarted: 21,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 9.27,
      completedEquipmentWorkOrders: 30,
      totalOpenEquipmentWorkOrders: 1,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 1,
    },
  },
  {
    name: "Hazlet",
    input: {
      totalMonitoredAssets: 144,
      workOrdersStarted: 18,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 13.15,
      completedEquipmentWorkOrders: 39,
      totalOpenEquipmentWorkOrders: 1,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 0,
    },
  },
  {
    name: "Howell",
    input: {
      totalMonitoredAssets: 51,
      workOrdersStarted: 10,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 17.6,
      completedEquipmentWorkOrders: 15,
      totalOpenEquipmentWorkOrders: 0,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 0,
    },
  },
  {
    name: "Jackson",
    input: {
      totalMonitoredAssets: 155,
      workOrdersStarted: 30,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 21.17,
      completedEquipmentWorkOrders: 42,
      totalOpenEquipmentWorkOrders: 0,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 1,
    },
  },
  {
    name: "Marlboro",
    input: {
      totalMonitoredAssets: 181,
      workOrdersStarted: 38,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 12.36,
      completedEquipmentWorkOrders: 50,
      totalOpenEquipmentWorkOrders: 3,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 1,
    },
  },
  {
    name: "Middleton",
    input: {
      totalMonitoredAssets: 115,
      workOrdersStarted: 19,
      preventiveMaintenanceTouches: 0,
      memberReportingAvailable: false,
      averageDaysToClose: 4.72,
      completedEquipmentWorkOrders: 39,
      totalOpenEquipmentWorkOrders: 0,
      olderThan15Days: 0,
      olderThan30Days: 0,
      olderThan45Days: 0,
      assetsWith3PlusRepairs: 1,
    },
  },
];

export const defaultScenarioInput: ScenarioInput = { ...DEFAULT_LOCATION_DATASET[0].input };
